const sharedAl01 = {
  dataset: "S1",
  canonicalWorkItemId: "WI-AL01-CEILING-001",
  itemCode: "AL01",
  canonicalTerm: "鋁質方形扣板天花",
  canonicalDescription: "AL01 鋁質方形扣板天花 600×600 厚0.6mm 白色沖孔",
  aliases: ["鋁扣板天花", "鋁扣天花", "aluminium ceiling tile", "metal ceiling", "false ceiling"],
  standardUnit: "m²",
  project: "P54425 澳門威尼斯大囍餐廳",
  confirmationEvidence: "v004 item-level 人工確認｜2026-07-31",
  date: "2026-06-16",
};

const SOURCE_DOCUMENT_HASHES = {
  "創澳_AL01_報價_0428_ST.pdf": "80f3b9a16f40e75575360eecbd8cb1b7bff191c08bb5ed3335e6d4b7f4660dd0",
  "創澳_AL01_補充報價.pdf": "28500f8e07348baa89f35f881ebdb40289eb02157113c6a664ee0c9726f95345",
  "JWQ-2026-0478.pdf": "a298bdd4ff7cf3b1d1f0bb4e954eb486c2308f832ceee07e1605aeb6f8047404",
  "JWQ-2026-0511.pdf": "12985f41b989464793f6b4f5c546397c7de6f0c205101ec91b955fb289314281",
  "JWQ-2026-0533.pdf": "e0cca1271e2de1e42e1d4df870fab3c9e31e1f2e21c0bc8dfbaa088226edfa63",
  "李明_AL01_報價.pdf": "3347ec4b1933b18521ef78a4d983c9c1abd4823e12979001b84b2e85aef3eeb5",
  "JWQ-2026-0544.pdf": "3e642cecb6e7c92c96356a0bb420038f29ee5278c5b4e68590d7e8136f73f3a9",
  "富騰_AL01_材料報價.xlsx": "e3b2fe0f9acb37838e8f8bac40afd5f5192187de855d0ba90b5e41f9a0c89e03",
  "鋁扣板_Signed.pdf": "709fc701995b07d2a424ea391944c3e8485047bc2e67be1012ec23f5b8d6bf3c",
  "ABC_Metal_AL01_Quotation.xlsx": "85978a841800943cedc67cb72511cca1c48ea553a50b2e3fb141aec3eb789e5c",
  "P54425_Costing.xlsx": "c7f819c32d3c172c939fe38472676dc5deb8c5643f5fcb9e7b00d09246279ce7",
  "P54425_Client_Quotation.xlsx": "a6aeff1ce3c0ac7e91de71ff1187e6887779326070e0ce924b94903a4b05840b",
  "P53218_Final_Quotation.xlsx": "3046d8e09e776dd6fa282b24ac04478848a8faf83a44635e15620f2639b759ca",
  "P52680_Final_Quotation.xlsx": "681e8cf86dbf3ec984de01a0b87312f12d46b183a08dd1ddaf6f5dd913d02d9c",
};

export const DATASETS = {
  subcontractors: {
    code: "S1",
    label: "判頭報價",
    route: "/search/subcontractors",
    description: "判頭原文、標準報價類型與工項範圍",
  },
  suppliers: {
    code: "S2",
    label: "供應商報價",
    route: "/search/suppliers",
    description: "供應商報價、實際支出、數量與運輸基準",
  },
  historical: {
    code: "S3",
    label: "歷史出街價",
    route: "/search/historical-prices",
    description: "開工估算、實際成本與歷史對客出街價",
  },
};

const RAW_PRICE_RECORDS = [
  {
    ...sharedAl01,
    id: "S1-CA-AL01-001",
    dataset: "S1",
    rawDescription: "連工包杆及拉爆，鋁扣板面材另供",
    counterparty: "創澳工程有限公司",
    mopValue: 200,
    originalCurrency: "MOP",
    originalValue: 200,
    exchangeRateUsed: 1,
    priceSemantic: "SUBCONTRACTOR_QUOTED_RATE",
    priceSemanticLabel: "判頭報價單價",
    standardQuoteType: "人工＋底料",
    scopeSignature: "LABOUR_SUBFRAME",
    scopeLabel: "人工、吊杆及拉爆；不含鋁扣板面材",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "來源逐行報價單價",
    transportInclusion: "NOT_APPLICABLE",
    transportLabel: "不適用",
    used: true,
    supplierQuoteQty: 19,
    clientProjectQty: 19,
    qtyRelationship: "相同",
    totalMop: 3800,
    sourceDocument: "創澳_AL01_報價_0428_ST.pdf",
    sourceLocator: "P.03 · R.08",
  },
  {
    ...sharedAl01,
    id: "S1-CA-AL01-002",
    rawDescription: "包杆及安裝，面板由客方供應",
    counterparty: "創澳工程有限公司",
    mopValue: 195,
    originalCurrency: "MOP",
    originalValue: 195,
    exchangeRateUsed: 1,
    priceSemantic: "SUBCONTRACTOR_QUOTED_RATE",
    priceSemanticLabel: "判頭報價單價",
    standardQuoteType: "人工＋底料",
    scopeSignature: "LABOUR_SUBFRAME",
    scopeLabel: "人工、吊杆及安裝；不含面板",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "來源逐行報價單價",
    transportInclusion: "NOT_APPLICABLE",
    transportLabel: "不適用",
    used: false,
    supplierQuoteQty: 21.24,
    clientProjectQty: 19,
    qtyRelationship: "不同",
    totalMop: 3705,
    sourceDocument: "創澳_AL01_補充報價.pdf",
    sourceLocator: "P.01 · R.05",
  },
  {
    ...sharedAl01,
    id: "S1-JWQ-0478",
    rawDescription: "鋁質方形扣板天花 600x600 厚0.6mm 白色沖孔，淨工",
    counterparty: "聯贏工程有限公司",
    mopValue: 158.75,
    originalCurrency: "MOP",
    originalValue: 158.75,
    exchangeRateUsed: 1,
    priceSemantic: "SUBCONTRACTOR_QUOTED_RATE",
    priceSemanticLabel: "判頭報價單價",
    standardQuoteType: "只包人工",
    scopeSignature: "LABOUR_ONLY",
    scopeLabel: "只包安裝人工；材料及運輸另供",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "來源逐行報價單價",
    transportInclusion: "NOT_APPLICABLE",
    transportLabel: "不適用",
    used: false,
    supplierQuoteQty: 19,
    clientProjectQty: 19,
    qtyRelationship: "相同",
    totalMop: 3016.25,
    sourceDocument: "JWQ-2026-0478.pdf",
    sourceLocator: "P.02 · R.12",
  },
  {
    ...sharedAl01,
    id: "S1-JWQ-0511",
    rawDescription: "AL01 600x600鋁扣板天花，剩工",
    counterparty: "聯贏工程有限公司",
    mopValue: 162.6,
    originalCurrency: "MOP",
    originalValue: 162.6,
    exchangeRateUsed: 1,
    priceSemantic: "SUBCONTRACTOR_QUOTED_RATE",
    priceSemanticLabel: "判頭報價單價",
    standardQuoteType: "只包人工",
    scopeSignature: "LABOUR_ONLY",
    scopeLabel: "只包安裝人工；材料及運輸另供",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "來源逐行報價單價",
    transportInclusion: "NOT_APPLICABLE",
    transportLabel: "不適用",
    used: true,
    supplierQuoteQty: 21.24,
    clientProjectQty: 19,
    qtyRelationship: "不同",
    totalMop: 3089.4,
    sourceDocument: "JWQ-2026-0511.pdf",
    sourceLocator: "P.12 · R.25",
  },
  {
    ...sharedAl01,
    id: "S1-JWQ-0533",
    rawDescription: "鋁質方形扣板天花安裝，不包面板及運輸",
    counterparty: "聯贏工程有限公司",
    mopValue: 165.8,
    originalCurrency: "MOP",
    originalValue: 165.8,
    exchangeRateUsed: 1,
    priceSemantic: "SUBCONTRACTOR_QUOTED_RATE",
    priceSemanticLabel: "判頭報價單價",
    standardQuoteType: "只包人工",
    scopeSignature: "LABOUR_ONLY",
    scopeLabel: "只包安裝人工；材料及運輸另供",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "來源逐行報價單價",
    transportInclusion: "NOT_APPLICABLE",
    transportLabel: "不適用",
    used: false,
    supplierQuoteQty: 19,
    clientProjectQty: 19,
    qtyRelationship: "相同",
    totalMop: 3150.2,
    sourceDocument: "JWQ-2026-0533.pdf",
    sourceLocator: "P.04 · R.18",
  },
  {
    ...sharedAl01,
    id: "S1-LM-AL01-001",
    rawDescription: "鋁扣天花安裝，只包人工；材料及運輸另供",
    counterparty: "李明裝修工程",
    mopValue: 180,
    originalCurrency: "MOP",
    originalValue: 180,
    exchangeRateUsed: 1,
    priceSemantic: "SUBCONTRACTOR_QUOTED_RATE",
    priceSemanticLabel: "判頭報價單價",
    standardQuoteType: "只包人工",
    scopeSignature: "LABOUR_ONLY",
    scopeLabel: "只包安裝人工；材料及運輸另供",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "來源逐行報價單價",
    transportInclusion: "NOT_APPLICABLE",
    transportLabel: "不適用",
    used: false,
    supplierQuoteQty: 19,
    clientProjectQty: 19,
    qtyRelationship: "相同",
    totalMop: 3420,
    sourceDocument: "李明_AL01_報價.pdf",
    sourceLocator: "P.01 · R.06",
  },
  {
    ...sharedAl01,
    id: "S1-JWQ-0544",
    rawDescription: "AL01 鋁扣板天花剩工，不包材料及運輸",
    counterparty: "聯贏工程有限公司",
    mopValue: 169.25,
    originalCurrency: "MOP",
    originalValue: 169.25,
    exchangeRateUsed: 1,
    priceSemantic: "SUBCONTRACTOR_QUOTED_RATE",
    priceSemanticLabel: "判頭報價單價",
    standardQuoteType: "只包人工",
    scopeSignature: "LABOUR_ONLY",
    scopeLabel: "只包安裝人工；材料及運輸另供",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "來源逐行報價單價",
    transportInclusion: "NOT_APPLICABLE",
    transportLabel: "不適用",
    used: false,
    supplierQuoteQty: 19,
    clientProjectQty: 19,
    qtyRelationship: "相同",
    totalMop: 3215.75,
    sourceDocument: "JWQ-2026-0544.pdf",
    sourceLocator: "P.03 · R.09",
  },
  {
    ...sharedAl01,
    id: "S2-FT-AL01-QUOTE",
    dataset: "S2",
    rawDescription: "Aluminum square ceiling tile 600×600×0.6mm perforated white",
    counterparty: "富騰建材有限公司",
    mopValue: 172.5,
    originalCurrency: "CNY",
    originalValue: 150,
    exchangeRateUsed: 1.15,
    priceSemantic: "SUPPLIER_QUOTED_UNIT_PRICE",
    priceSemanticLabel: "供應商報價單價",
    standardQuoteType: "材料報價",
    scopeSignature: "MATERIAL_ONLY",
    scopeLabel: "鋁扣板面材；不含運輸及安裝",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "150 CNY × 1.15",
    transportInclusion: "EXCLUDED",
    transportLabel: "不包含",
    used: true,
    supplierQuoteQty: 21.24,
    clientProjectQty: 19,
    qtyRelationship: "不同",
    totalMop: 3663.9,
    sourceDocument: "富騰_AL01_材料報價.xlsx",
    sourceLocator: "報價明細 · Row 14",
  },
  {
    ...sharedAl01,
    id: "S2-FT-AL01-ACTUAL",
    dataset: "S2",
    rawDescription: "AL01 鋁扣板實際採購支出（簽署總額）",
    counterparty: "富騰建材有限公司",
    mopValue: 168.42,
    originalCurrency: "MOP",
    originalValue: 3200,
    exchangeRateUsed: 1,
    priceSemantic: "ACTUAL_EXPENSE_PER_PROJECT_QUANTITY",
    priceSemanticLabel: "有效實際成本單價",
    standardQuoteType: "實際支出",
    scopeSignature: "MATERIAL_ONLY",
    scopeLabel: "面材實際支出；不含判頭人工及運輸",
    unitCostBasis: "ACTUAL_EXPENSE_DIV_PROJECT_QTY",
    unitCostBasisLabel: "MOP 3,200.00 ÷ 19.00 m²",
    transportInclusion: "EXCLUDED",
    transportLabel: "不包含",
    used: true,
    supplierQuoteQty: 21.24,
    clientProjectQty: 19,
    qtyRelationship: "不同",
    totalMop: 3200,
    sourceDocument: "鋁扣板_Signed.pdf",
    sourceLocator: "P.02 · R.12",
  },
  {
    ...sharedAl01,
    id: "S2-ABC-AL01-QUOTE",
    dataset: "S2",
    rawDescription: "600×600 perforated aluminium ceiling tile, white finish",
    counterparty: "ABC Metal Supplies",
    project: "P54802 澳門商場翻新工程",
    mopValue: 176.8,
    originalCurrency: "HKD",
    originalValue: 171.65,
    exchangeRateUsed: 1.03,
    priceSemantic: "SUPPLIER_QUOTED_UNIT_PRICE",
    priceSemanticLabel: "供應商報價單價",
    standardQuoteType: "材料報價",
    scopeSignature: "MATERIAL_ONLY",
    scopeLabel: "鋁扣板面材；不含運輸及安裝",
    unitCostBasis: "SOURCE_QUOTED_UNIT_RATE",
    unitCostBasisLabel: "171.65 HKD × 1.03",
    transportInclusion: "EXCLUDED",
    transportLabel: "不包含",
    used: false,
    supplierQuoteQty: 24,
    clientProjectQty: 24,
    qtyRelationship: "相同",
    totalMop: 4243.2,
    sourceDocument: "ABC_Metal_AL01_Quotation.xlsx",
    sourceLocator: "Quote · Row 11",
  },
  {
    ...sharedAl01,
    id: "S2-FT-AL01-TRANSPORT",
    dataset: "S2",
    rawDescription: "AL01 鋁扣板運輸費",
    counterparty: "富騰建材有限公司",
    mopValue: 17.25,
    originalCurrency: "MOP",
    originalValue: 17.25,
    exchangeRateUsed: 1,
    priceSemantic: "TRANSPORT_UNIT_COST",
    priceSemanticLabel: "運輸單位成本",
    standardQuoteType: "運輸報價",
    scopeSignature: "TRANSPORT_ONLY",
    scopeLabel: "只含本材料運輸",
    unitCostBasis: "FIXED_TRANSPORT_DIV_PROJECT_QTY",
    unitCostBasisLabel: "指定運輸金額 ÷ Project 數量",
    transportInclusion: "SEPARATE_LINE",
    transportLabel: "獨立運輸行",
    used: true,
    supplierQuoteQty: 21.24,
    clientProjectQty: 19,
    qtyRelationship: "不同",
    totalMop: 327.75,
    sourceDocument: "P54425_Costing.xlsx",
    sourceLocator: "1126 · Row 33",
  },
  {
    ...sharedAl01,
    id: "S2-FT-AL01-ALLIN",
    dataset: "S2",
    rawDescription: "AL01 材料連運輸成本",
    counterparty: "富騰建材有限公司",
    mopValue: 189.75,
    originalCurrency: "MOP",
    originalValue: 189.75,
    exchangeRateUsed: 1,
    priceSemantic: "MATERIAL_WITH_TRANSPORT_UNIT_COST",
    priceSemanticLabel: "材料連運輸單價",
    standardQuoteType: "材料報價",
    scopeSignature: "MATERIAL_WITH_TRANSPORT",
    scopeLabel: "面材及該材料運輸；不含安裝",
    unitCostBasis: "QUOTE_RATE_PLUS_TRANSPORT",
    unitCostBasisLabel: "172.50 + 17.25",
    transportInclusion: "INCLUDED",
    transportLabel: "已包含",
    used: true,
    supplierQuoteQty: 21.24,
    clientProjectQty: 19,
    qtyRelationship: "不同",
    totalMop: 3605.25,
    sourceDocument: "P54425_Costing.xlsx",
    sourceLocator: "1126 · Row 33",
  },
  {
    ...sharedAl01,
    id: "S2-FT-AL01-PRINTED",
    dataset: "S2",
    rawDescription: "鋁扣板報價印刷總額（只作獨立價格語義）",
    counterparty: "富騰建材有限公司",
    mopValue: 3240,
    originalCurrency: "MOP",
    originalValue: 3240,
    exchangeRateUsed: 1,
    priceSemantic: "PRINTED_DOCUMENT_TOTAL",
    priceSemanticLabel: "印刷文件總額",
    standardQuoteType: "文件總額",
    standardUnit: "項",
    scopeSignature: "MATERIAL_ORDER_TOTAL",
    scopeLabel: "來源印刷材料總額；已確認不含運輸及安裝",
    unitCostBasis: "SOURCE_PRINTED_TOTAL",
    unitCostBasisLabel: "來源文件總額",
    transportInclusion: "EXCLUDED",
    transportLabel: "不包含",
    used: false,
    supplierQuoteQty: 21.24,
    clientProjectQty: 19,
    qtyRelationship: "不同",
    totalMop: 3240,
    sourceDocument: "鋁扣板_Signed.pdf",
    sourceLocator: "P.02 · Total",
  },
  {
    ...sharedAl01,
    id: "S3-P54425-OPENING",
    dataset: "S3",
    rawDescription: "AL01 開工時材料比較基準",
    counterparty: "JW Costing Team",
    mopValue: 150,
    originalCurrency: "MOP",
    originalValue: 150,
    exchangeRateUsed: 1,
    priceSemantic: "OPENING_ESTIMATED_COST_UNIT",
    priceSemanticLabel: "開工時估算成本單價",
    standardQuoteType: "Project Costing",
    scopeSignature: "MATERIAL_ESTIMATE",
    scopeLabel: "開工時材料比較；不含運輸及人工",
    unitCostBasis: "PROJECT_OPENING_ESTIMATE",
    unitCostBasisLabel: "Project Costing 已確認估算",
    transportInclusion: "EXCLUDED",
    transportLabel: "不包含",
    used: true,
    supplierQuoteQty: 21.24,
    clientProjectQty: 19,
    qtyRelationship: "不同",
    totalMop: 2850,
    sourceDocument: "P54425_Costing.xlsx",
    sourceLocator: "1126 · Row 33",
  },
  {
    ...sharedAl01,
    id: "S3-P54425-OUTGOING",
    dataset: "S3",
    rawDescription: "AL01 客戶報價出街單價",
    counterparty: "JW Project P54425",
    mopValue: 438,
    originalCurrency: "MOP",
    originalValue: 438,
    exchangeRateUsed: 1,
    priceSemantic: "OUTGOING_UNIT_PRICE",
    priceSemanticLabel: "歷史出街單價",
    standardQuoteType: "對客出街價",
    scopeSignature: "CLIENT_BQ_COMPLETE_SCOPE",
    scopeLabel: "材料、運輸、人工及加成的對客單價",
    unitCostBasis: "APPROVED_PROJECT_ACTUAL_FINAL",
    unitCostBasisLabel: "已批准 Project Actual Final",
    transportInclusion: "INCLUDED",
    transportLabel: "已包含",
    used: true,
    supplierQuoteQty: 19,
    clientProjectQty: 19,
    qtyRelationship: "相同",
    totalMop: 8322,
    sourceDocument: "P54425_Client_Quotation.xlsx",
    sourceLocator: "1126 · Row 33",
  },
  {
    ...sharedAl01,
    id: "S3-P54425-ROW-TOTAL",
    dataset: "S3",
    rawDescription: "AL01 Project Costing row 33 成本組合單價",
    counterparty: "JW Project P54425",
    mopValue: 389.75,
    originalCurrency: "MOP",
    originalValue: 389.75,
    exchangeRateUsed: 1,
    priceSemantic: "PROJECT_COST_BUILDUP_UNIT",
    priceSemanticLabel: "Project成本組合單價",
    standardQuoteType: "Project Costing",
    scopeSignature: "MATERIAL_TRANSPORT_SUBCONTRACT",
    scopeLabel: "材料、運輸及判頭成本組合",
    unitCostBasis: "CONFIRMED_COST_BUILDUP",
    unitCostBasisLabel: "189.75 + 200.00",
    transportInclusion: "INCLUDED",
    transportLabel: "已包含",
    used: true,
    supplierQuoteQty: 19,
    clientProjectQty: 19,
    qtyRelationship: "相同",
    totalMop: 7405.25,
    sourceDocument: "P54425_Costing.xlsx",
    sourceLocator: "1126 · Row 33",
  },
  {
    ...sharedAl01,
    id: "S3-P53218-OUTGOING",
    dataset: "S3",
    rawDescription: "AL01 金屬天花供應及安裝",
    counterparty: "JW Project P53218",
    project: "P53218 金沙城中心翻新工程",
    mopValue: 421.5,
    originalCurrency: "MOP",
    originalValue: 421.5,
    exchangeRateUsed: 1,
    priceSemantic: "OUTGOING_UNIT_PRICE",
    priceSemanticLabel: "歷史出街單價",
    standardQuoteType: "對客出街價",
    scopeSignature: "CLIENT_BQ_COMPLETE_SCOPE",
    scopeLabel: "材料、運輸、人工及加成的對客單價",
    unitCostBasis: "APPROVED_PROJECT_ACTUAL_FINAL",
    unitCostBasisLabel: "已批准 Project Actual Final",
    transportInclusion: "INCLUDED",
    transportLabel: "已包含",
    used: true,
    supplierQuoteQty: 32.5,
    clientProjectQty: 32.5,
    qtyRelationship: "相同",
    totalMop: 13698.75,
    sourceDocument: "P53218_Final_Quotation.xlsx",
    sourceLocator: "Ceiling · Row 18",
  },
  {
    ...sharedAl01,
    id: "S3-P52680-OUTGOING",
    dataset: "S3",
    rawDescription: "600×600 白色沖孔鋁扣板天花全套",
    counterparty: "JW Project P52680",
    project: "P52680 路氹酒店客房工程",
    mopValue: 445,
    originalCurrency: "MOP",
    originalValue: 445,
    exchangeRateUsed: 1,
    priceSemantic: "OUTGOING_UNIT_PRICE",
    priceSemanticLabel: "歷史出街單價",
    standardQuoteType: "對客出街價",
    scopeSignature: "CLIENT_BQ_COMPLETE_SCOPE",
    scopeLabel: "材料、運輸、人工及加成的對客單價",
    unitCostBasis: "APPROVED_PROJECT_ACTUAL_FINAL",
    unitCostBasisLabel: "已批准 Project Actual Final",
    transportInclusion: "INCLUDED",
    transportLabel: "已包含",
    used: false,
    supplierQuoteQty: 48,
    clientProjectQty: 48,
    qtyRelationship: "相同",
    totalMop: 21360,
    sourceDocument: "P52680_Final_Quotation.xlsx",
    sourceLocator: "AL · Row 22",
  },
];

export const PRICE_RECORDS = RAW_PRICE_RECORDS.map((record) => ({
  ...record,
  sourceHash: SOURCE_DOCUMENT_HASHES[record.sourceDocument],
}));

export const INITIAL_SELECTION = [
  "S1-CA-AL01-001",
  "S1-CA-AL01-002",
  "S1-JWQ-0478",
  "S1-JWQ-0511",
];

export const THRESHOLD_DEMO_SELECTION = [
  "S1-JWQ-0478",
  "S1-JWQ-0511",
  "S1-JWQ-0533",
  "S1-JWQ-0544",
  "S2-FT-AL01-QUOTE",
  "S2-ABC-AL01-QUOTE",
  "S3-P54425-OUTGOING",
];

export const ADMIN_ACCOUNTS = Array.from({ length: 10 }, (_, index) => ({
  id: `user${index + 1}`,
  role: "SEARCH_USER",
  status: index === 8 ? "LOCKED" : "ACTIVE",
  lastSecurityEvent: index === 8 ? "2026-07-31 16:42 鎖定" : "2026-07-31 登入成功",
}));

export const ANONYMOUS_FEEDBACK = [
  { id: "FB-021", recordId: "S1-JWQ-0478", route: "/search/subcontractors", reason: "名稱不符", count: 4, window: "30日", status: "待管理員覆核" },
  { id: "FB-018", recordId: "S2-FT-AL01-ACTUAL", route: "/search/suppliers", reason: "數量基準不清", count: 3, window: "30日", status: "待業務批准" },
  { id: "FB-011", recordId: "S3-P54425-OUTGOING", route: "/search/historical-prices", reason: "工項不符", count: 2, window: "30日", status: "未達門檻" },
];
